name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@01ad6d2663fa6fc4add68e686ff72c415a2cf3c3
      - name: Publish package
        uses: gradle/gradle-build-action@3bfe3a46584a206fb8361cdedd0647b0c4204232
        with:
          arguments: publish -Pversion=${{ github.event.release.tag_name }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_BASE64_PRIVATE_KEY: ${{ secrets.MAVEN_BASE64_PRIVATE_KEY }}
          MAVEN_KEY_PASSPHRASE: ${{ secrets.MAVEN_KEY_PASSPHRASE }}